version: "3.7"


services:

  postgres:
    container_name: pytorch_breed_clf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    networks:
      - backend

networks:
  backend:
